<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>txt</string>
	</array>
	<key>name</key>
	<string>TinyTextAdventure</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ssraw</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>item text properties</string>
			<key>match</key>
			<string>(item (name|description|mid sentence cased name|countable noun prefix|successful use message|examine message|label):)(.*)</string>
			<key>name</key>
			<string>item_text_properties.text.tinytextadventure</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ssraw</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>item with id properties</string>
			<key>match</key>
			<string>(item (id|can be used with):)(.*)</string>
			<key>name</key>
			<string>item_with_id_properties.text.tinytextadventure</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ssraw</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ssraw</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>item talk action:change location description</string>
			<key>match</key>
			<string>((item) (talk action in response to):(.*):change location description:(.*):)(.*)</string>
			<key>name</key>
			<string>itemtalkaction_changelocationdescription.text.tinytextadventure</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ssraw</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>item talk action:change item description</string>
			<key>match</key>
			<string>(item (talk action in response to):(.*):change item description:)(.*)</string>
			<key>name</key>
			<string>itemtalkaction_changeitemdescription.text.tinytextadventure</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ssraw</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>item talk use action:change item visibility</string>
			<key>match</key>
			<string>(item (talk action in response to):(.*):change item visibility:(.*):)(.*)</string>
			<key>name</key>
			<string>itemtalkuseaction_changeitemvisibility.text.tinytextadventure</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ssraw</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>item talk use action:change exit visibility</string>
			<key>match</key>
			<string>(item (talk action in response to):(.*):change exit visibility:(.*):)(.*)</string>
			<key>name</key>
			<string>itemtalkuseaction_changeexitvisibilityext.tinytextadventure</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ssraw</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>item talk generic action</string>
			<key>match</key>
			<string>(item (talk action in response to):(.*):.*:(.*))</string>
			<key>name</key>
			<string>itemtalkgenericaction.text.tinytextadventure</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ssraw</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ssraw</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>item or exit use action:change location description</string>
			<key>match</key>
			<string>((item|exit) (.* action.*):change location description:(.*):)(.*)</string>
			<key>name</key>
			<string>itemorexituseaction_changelocationdescription.text.tinytextadventure</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ssraw</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>item action:change item description</string>
			<key>match</key>
			<string>(item (.* action.*):change item description:(.*))</string>
			<key>name</key>
			<string>itemaction_changeitemdescription.text.tinytextadventure</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ssraw</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ssraw</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>item or exit use action:change item visibility</string>
			<key>match</key>
			<string>((item|exit) (.* action.*):change item visibility:(.*):)(.*)</string>
			<key>name</key>
			<string>itemorexituseaction_changeitemvisibility.text.tinytextadventure</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ssraw</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ssraw</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>item or exit use action:change exit visibility</string>
			<key>match</key>
			<string>((item|exit) (.* action.*):change exit visibility:(.*):)(.*)</string>
			<key>name</key>
			<string>itemorexituseaction_changeexitvisibilityext.tinytextadventure</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ssraw</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ssraw</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>item or exit generic action</string>
			<key>match</key>
			<string>((item|exit) (.* action.*):.*:(.*))</string>
			<key>name</key>
			<string>itemorexitgenericaction.text.tinytextadventure</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ssraw</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>item talk initial phrase</string>
			<key>match</key>
			<string>(item (talk initial phrase):(.*):(.*):(.*))</string>
			<key>name</key>
			<string>itemtalkinitialphrase.text.tinytextadventure</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ssraw</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>item talk reponse to</string>
			<key>match</key>
			<string>(item (talk response to):(.*):(.*))</string>
			<key>name</key>
			<string>itemtalkreponseto.text.tinytextadventure</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ssraw</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>item talk reponse to</string>
			<key>match</key>
			<string>(item (talk follow up phrase to):(.*):(.*):(.*):(.*))</string>
			<key>name</key>
			<string>itemtalkreponseto.text.tinytextadventure</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ssraw</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>item talk reponse to</string>
			<key>match</key>
			<string>(item (talk follow up phrase to):(.*):(.*))</string>
			<key>name</key>
			<string>itemtalkreponseto.text.tinytextadventure</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ssraw</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>location area id</string>
			<key>match</key>
			<string>(location (area id):)(.*)</string>
			<key>name</key>
			<string>locationareaid.text.tinytextadventure</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ssraw</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>location area name</string>
			<key>match</key>
			<string>(location (area name):)(.*)</string>
			<key>name</key>
			<string>locationareaname.text.tinytextadventure</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ssraw</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>location text properties</string>
			<key>match</key>
			<string>(location (description):)(.*)</string>
			<key>name</key>
			<string>location_text_properties.text.tinytextadventure</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ssraw</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>text to show on first entry</string>
			<key>match</key>
			<string>((text to show on first entry):)(.*)</string>
			<key>name</key>
			<string>texttoshowonfirstentry.text.tinytextadventure</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ssraw</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>location with id properties</string>
			<key>match</key>
			<string>(location (id|area id):)(.*)</string>
			<key>name</key>
			<string>location_with_id_properties.text.tinytextadventure</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ssraw</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>exit text properties</string>
			<key>match</key>
			<string>(exit (label):)(.*)</string>
			<key>name</key>
			<string>exit_text_properties.text.tinytextadventure</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ssraw</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>exit  with id properties</string>
			<key>match</key>
			<string>(exit (destination|id):)(.*)</string>
			<key>name</key>
			<string>exit_with_id_properties.text.tinytextadventure</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ssraw</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ssraw</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>generic item, exit or location identifier</string>
			<key>match</key>
			<string>((item|exit|location) ([A-Za-z_\- ]+):)</string>
			<key>name</key>
			<string>item_exit_or_location_identifier.text.tinytextadventure</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ssraw</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>generic identifier</string>
			<key>match</key>
			<string>([A-Za-z_\- ]+:)</string>
			<key>name</key>
			<string>generic_identifier.text.tinytextadventure</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>direction</string>
			<key>match</key>
			<string>(East|West|South|North)</string>
			<key>name</key>
			<string>direction.text.tinytextadventure</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>visibility</string>
			<key>match</key>
			<string>(visible|invisible)</string>
			<key>name</key>
			<string>visibility.text.tinytextadventure</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>section headers</string>
			<key>match</key>
			<string>(PROPERTIES|INVENTORY ITEM|LOCATION AREA|LOCATION|EXIT|ITEM)</string>
			<key>name</key>
			<string>section_headers.text.tinytextadventure</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.tinytextadventure</string>
	<key>uuid</key>
	<string>32d880ef-fed2-4e62-9eab-0d185544cb6d</string>
</dict>
</plist>
